### ISSUE TITLE
Indoor Power is wrong (resting=1500W)

### ISSUE THREAD

**Issue by clintiepoo** [apetrycki/daikinskyport#84] opened 2023-10-31 00:17 UTC
My app reports my indoor power while the system is at rest as 1500W. I think this is possibly an offset issue in the software, and the value past that is being multiplied. The max I have measured is 1130W. I can provide more information as needed. 

![image](https://github.com/apetrycki/daikinskyport/assets/33547246/fbb562a8-bf85-41b1-8236-ba306706f430)

**Comment by apetrycki** [comment] 2023-10-31 02:30
Get the raw reading from the API using commands from the API info and what it should be from a power sensor or ammeter.  Take multiple values at different loads.  I don't have power readings on my unit, but there is a feature request for energy sensors you can contribute to with a couple people who do.  1500 doesn't seem like a correct value from the API compared to what others are seeing.  Looking at the code, I don't see any manipulation to the raw value, so the raw should be equal to what's in HA.  Also post your model numbers for your units.

**Comment by clintiepoo** [comment] 2023-10-31 12:11
I’m willing to help if you point me in the right direction on how to read the api values. 

The furnace I’m having issues with is: Daikin DM97MC1205DNAA
Communicating 97% Modulating
Furnace

I also have this heat pump: Daikin DZ6VSA481E
Communicating 17 SEER Variable Speed
2023 HP

**Comment by apetrycki** [comment] 2023-10-31 18:37
https://github.com/apetrycki/daikinskyport/blob/master/API_info.md explains how to use the API.  Is the heat pump producing proper power values?

**Comment by clintiepoo** [comment] 2023-10-31 19:52
> https://github.com/apetrycki/daikinskyport/blob/master/API_info.md explains how to use the API. Is the heat pump producing proper power values?

As far as I know, the heat pump is producing the proper values. This is a new system for me - glad for your work getting it integrated to HASS.

**Comment by apetrycki** [comment] 2023-10-31 21:00
It looks like you have the same unit as the other guys in this thread: https://github.com/apetrycki/daikinskyport/issues/31

I don't think they're seeing the same thing you are, so it may be something wrong with your unit.  I'd ask in that thread and see what they say.  Let me know what the API raw value is when idle.  You also might want to try rebooting the thermostat and your units to see if it's a software glitch.

**Comment by clintiepoo** [comment] 2023-10-31 22:26
> It looks like you have the same unit as the other guys in this thread: #31
> 
> I don't think they're seeing the same thing you are, so it may be something wrong with your unit. I'd ask in that thread and see what they say. Let me know what the API raw value is when idle. You also might want to try rebooting the thermostat and your units to see if it's a software glitch.

I rebooted the unit - no change. I think this is the correct value. With the unit at rest, I'm seeing 1500 as the value. 

`"ctIndoorPower":1500`

**Comment by clintiepoo** [comment] 2023-10-31 23:30
I took some measurements. Here's what I found:

`
|Fan Speed | Measured (Amp) | Measured (converted to Watt) | ctIndoorPower |   
|------|----------------|-----------------|---------------|
| Off  | 0.2            | 24              | 1500          |  
| Low  | 0.55           | 66              | 620           |  
| Med  | 3.21           | 385.2           | 3453          |  
| High | 8.97           | 1076.4          | 12500         |  
`

**Comment by clintiepoo** [comment] 2023-11-01 22:29
> Yeah, your off doesn't make sense. The other ones looks similar to what's posted in the other thread. I think there's something wrong with your unit if a reboot didn't help.
> 
> 65535 is the default value when there is no data. It's the max value of a 64k integer. I haven't decided if I should ignore that value or leave it so people know when the information is incorrect. I probably should ignore it for things like power where it'll screw up the daily kWh usage. Most other things it shouldn't really matter.

This makes sense to me. I wondered if you could also filter out 1500 if that’s a widespread issue, but if it’s just me that doesn’t make sense. I think filtering the maxed value is ok - it’s just noise. 

In general, the values look to be roughly 10x the power readings they should be. If you want to close this or merge into the other issue that’s fine.

**Comment by apetrycki** [comment] 2023-11-02 02:19
Duplicate of #31

**Closed by apetrycki** 2023-11-02 02:19 UTC
